# site settings
title: VM/76
description: >
  Lacking description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /blog/:categories/:title.html
timezone: Asia/Shanghai
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      style: post

# something extra
liquid:
  error_mode: warn
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true
  auto_ids: true
  entity_output: as_input
  smart_quotes:
    # ‘’“”
    # 我们不需要“智能”引号，自己就可以输入。
    - apos
    - apos
    - quot
    - quot
sass:
  style: compressed

# ‘serve’ command options
port: 8076
