# site settings
title: VM/76
description: >
  Lacking description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /blog/:categories/:title.html
timezone: Asia/Shanghai

# something extra
sass:
  style: compressed

# ‘serve’ command options
port: 8076

# GitHub defaults
kramdown:
  input: GFM
  hard_wrap: false
